version: "3.7"

services:
  shout-backend:
    container_name: shout-backend
    build: .
    ports:
      - 4000:4000
    restart: unless-stopped
  reservse-proxy:
    image: nginx:stable-alpine3.17-slim
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:4000
