version: "3.7"
services:
  letsencrypt:
    container_name: "certbot-service"
    image: certbot/certbot:v1.17.0
    command: sh -c "certbot certonly --expand --webroot -w /tmp/acme_challenge -d shout-back.0xwa.run --text --agree-tos --email ribbinpo@gmail.com --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme_challenge:/tmp/acme_challenge"
    environment:
      - TERM=xterm
