version: "3.7"

services:
  shout-backend:
    container_name: shout-backend
    build: .
    ports:
      - 4000:4000
    restart: unless-stopped
    networks:
      my-networks:
  reservse-proxy:
    container_name: nginx_reverse_proxy
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    ports:
      - 80:80
      - 443:443
    networks:
      my-networks:
networks:
  my-networks:
